### PR TITLE
Elasticsearch wireup

### PR DESCRIPTION
**Pull request by sokrahta**
Planned but not yet implemented: 
* logging

Requesting feedback about: 
* when we receive an upsert with a column not yet mapped, should we ...
  * fail the upsert
  * drop the unknown column(s)
  * automatically add a mapping
* what is the expected body format of resync and version calls?

[Review on Reviewable](https://reviewable.io/reviews/socrata/spandex/2)

### CODE REVIEW

**Comment by chitang** [comment]
My biggest question is how multiple indexes will be used.  Or will it always has only one "spandex".
Eventually, only one http call - suggest will stay right?  Other calls will go to spandex-secondary.

**Comment by znep** [comment]
Regarding "what is the expected body format of resync and version calls" I'm confused what you mean.  We have the Secondary trait.  You have to implement that trait then run in process in the secondary watcher.  I'm not sure how much we gain from turning those into HTTP calls...

**Comment by sokrahta** [comment]
will address json and config comments in the morning, 
secondary trait coming in a future pull req

**Comment by sokrahta** [comment]
@chitang ready for merge

**Pull request merged**
