### PR TITLE
Add some inchoate notes and changes to the readme

### PR DESCRIPTION
**Pull request by rantler**
Thanks again @urmilan!! :heart:

### CODE REVIEW

**Comment by urmilan** [comment]
Thanks @rantler, I'll flesh this out. From a frontend dev perspective, some of these config steps probably belong in the onramp script and its copy of soda2.conf.

**Comment by urmilan** [comment]
Hey @rantler, I've tried to flesh out/streamline some of the steps. Feel free to tweak as you see fit and merge when you've made the corresponding changes to the onramp scripts.

**Comment by rantler** [comment]
@urmilan ping pong back to you! If it looks good merge it!

**Comment by urmilan** [comment]
Thanks for the updates @sokrahta :+1:

**Comment by sokrahta** [comment]
gladly! another tweak to show the new endpoint syntax

**Pull request merged**
